[theme]
base = "light"
primaryColor = "#1c6fe0"
backgroundColor = "#f4f8ff"
secondaryBackgroundColor = "#e7f0ff"
textColor = "#14213f"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
