[theme]
primaryColor = "#186b5d"
backgroundColor = "#0a0e17"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e252d"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[server]
maxUploadSize = 200
enableXsrfProtection = true
